import * as consts from "./consts";

/**
 * @function
 * @param {Field} field
 * @return {boolean}
 */
export const isAutoGenerated = field =>
  field.directives[consts.PRIMARY_GENERATED_COLUMN] ? true : false;
